#!/usr/bin/env python3

"""
Count all kmers in a FASTA file
"""

from ContigCompute import FASTAReader
import sys

reader1 = FASTAReader( open(sys.argv[1]) ) #This is a function that returns an object AND was generated by us

length = []
i = 0
for i, line in enumerate(reader1):
    line.strip().split()
    if line.startswith(">"):
        continue
    else:
        length.append(len(line))
        i += 1
        
Average = (sum(length)/i)
n50i = i/2
n50 = length[n50i]
minimum = length[0]
maximum = length[i]

Max_Print = ("Maximum is" + maximum)
Min_Print = ("Minimum is" + minimum)
n50_Print = ("N50 is" + n50)
Avg_Print = ("Average is" + Average)


print(
    Max_Print
    Min_Print
    n50_Print
    Avg_Print
)
           
# for ide,s in reader1:
#     column = ide.rstrip("_").split("_")
#     #print(column[1])
#     count = 0
#     if int(column[1]) > 0:
#         count += 1
#     else:
#         continue
#     count_sum = sum(count)
#     print(count_sum)
#
#query to 1 k to 2 and target to 3

# kmers = {}
#
# for ident in reader1:
#     count = 0
#     if int(ident[1]) > 0:
#         count += 1
#     else:
#         continue
#     print(count)
    
# for ident1, sequence1 in reader2:
#     for i in range( 0, len(sequence1) - k + 1 ):
#         kmerQ = sequence1[i:i+k]
#         if kmerQ in kmers:
#             print(i, kmerQ, kmers[kmerQ])
        

    
            

                
#for kmer, count in sorted( kmers.items(), key=lambda t: t[1] ):
 #   print( kmer, count, sep="\t" ) #Allows us to iterate key and value 
    